/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Controlador.Sentencias_sql;
import Controlador.control_existencias;
import Modelo.Producto;
import conexionSQL.conexionSQL;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Fernanda
 */
public class Arqueo extends javax.swing.JDialog {

    private conexionSQL cc = new conexionSQL();  
    private Connection cn = cc.conexion();
    private control_existencias con = new control_existencias();
    private Sentencias_sql sen = new Sentencias_sql();
    private Object[][] datostabla;
    /**
     * Creates new form Arqueo
     */
    public Arqueo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAIdProducto = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        SpCantidad = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        TfCosto = new javax.swing.JTextField();
        BtVerProductos = new javax.swing.JButton();
        BtArqueo = new javax.swing.JButton();
        BtCancelar = new javax.swing.JButton();
        BtSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Id producto: ");

        jLabel2.setText("Arqueo de productos");

        TAIdProducto.setColumns(20);
        TAIdProducto.setRows(5);
        jScrollPane1.setViewportView(TAIdProducto);

        jLabel3.setText("Canditad de ingreso");

        jLabel4.setText("Costo :");

        TfCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfCostoActionPerformed(evt);
            }
        });

        BtVerProductos.setText("VER PRODUCTOS");
        BtVerProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtVerProductosActionPerformed(evt);
            }
        });

        BtArqueo.setText("Realizar arqueo");
        BtArqueo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtArqueoActionPerformed(evt);
            }
        });

        BtCancelar.setText("Cancelar");
        BtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCancelarActionPerformed(evt);
            }
        });

        BtSalir.setText("Salir");
        BtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtVerProductos)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(38, 38, 38)
                                .addComponent(TfCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(SpCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtArqueo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtSalir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(260, 260, 260))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(SpCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TfCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtVerProductos)
                    .addComponent(BtArqueo)
                    .addComponent(BtCancelar)
                    .addComponent(BtSalir))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     public void limpiar()
    {
       TAIdProducto.setText("");
       SpCantidad.setToolTipText("");
       TfCosto.setText("");
    }
    
    public void  bloquear_cajas()
    {
       TAIdProducto.setEnabled(false);
       SpCantidad.setEnabled(false);
       TfCosto.setEnabled(false);
       BtVerProductos.setEnabled(false);
       BtArqueo.setEnabled(false);
       BtCancelar.setEnabled(false);
    }
    private void BtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BtSalirActionPerformed

    private void BtArqueoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtArqueoActionPerformed
        // TODO add your handling code here:
        int cantidadValue = (Integer) SpCantidad.getValue();
        int idProducto = Integer.parseInt(getTAIdProducto().getText());
        ResultSet resultado = sen.buscarProducto(idProducto);
        Producto producto = con.resultSetToProducto(resultado);
        double newCosto = Double.parseDouble(getTfCosto().getText());
        boolean exito = con.realizarArqueo(idProducto, newCosto, cantidadValue);
        if(exito == true){
            ResultSet resultado2 = sen.buscarProducto(idProducto);
            Producto producto2 = con.resultSetToProducto(resultado2);
            Principal pri = new Principal();
            MostrarCambio mc = new MostrarCambio(pri, true);
            mc.mostrarCambiosArqueo(producto, producto2, idProducto);
            mc.setVisible(rootPaneCheckingEnabled);
        }
    }//GEN-LAST:event_BtArqueoActionPerformed

    private void BtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCancelarActionPerformed
        // TODO add your handling code here:
        limpiar();
        bloquear_cajas();
    }//GEN-LAST:event_BtCancelarActionPerformed

    private void TfCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfCostoActionPerformed

    private void BtVerProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtVerProductosActionPerformed
        Principal pri = new Principal();
        ListarProductos pro = new ListarProductos(pri, true);
        pro.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_BtVerProductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Arqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Arqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Arqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Arqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Arqueo dialog = new Arqueo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public JSpinner getSpCantidad() {
        return SpCantidad;
    }

    public void setSpCantidad(JSpinner SpCantidad) {
        this.SpCantidad = SpCantidad;
    }

    public JTextField getTfCosto() {
        return TfCosto;
    }

    public void setTfCosto(JTextField TfCosto) {
        this.TfCosto = TfCosto;
    }

    public JTextArea getTAIdProducto() {
        return TAIdProducto;
    }

    public void setTAIdProducto(JTextArea TAIdProducto) {
        this.TAIdProducto = TAIdProducto;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtArqueo;
    private javax.swing.JButton BtCancelar;
    private javax.swing.JButton BtSalir;
    private javax.swing.JButton BtVerProductos;
    private javax.swing.JSpinner SpCantidad;
    private javax.swing.JTextArea TAIdProducto;
    private javax.swing.JTextField TfCosto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
