/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Controlador.control_existencias;
import Modelo.Compra;
import Modelo.FormaPago;
import Modelo.Producto;
import Modelo.Proveedor;
import conexionSQL.conexionSQL;
import java.awt.List;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fernanda
 */
public class FacturacionCompra extends javax.swing.JDialog {

    private conexionSQL cc = new conexionSQL();  
    private Connection cn = cc.conexion();
    private control_existencias con = new control_existencias();
    private Object[][] datostabla;
    private Modelo.FacturacionCompraMemento memento;
    
    public FacturacionCompra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        con.combox(CBFormaPago, "formapago", "descripcionPago");
        TfFechaFacturacionCompra.setEnabled(false);
        TfValorTotal.setEnabled(false);
        TfNumFactura.setEnabled(false);
        String fecha = con.obtenerFecha();
        TfFechaFacturacionCompra.setText( fecha );
    }
    

        public void guardarEstado() {
        memento = new Modelo.FacturacionCompraMemento(
            TfFechaFacturacionCompra.getText(),
            TfValorTotal.getText(),
            TfDocumentoProveedor.getText(),
            TfProductos.getText()
        );
    }
    public void restaurarEstado() {
        if (memento != null) {
            TfFechaFacturacionCompra.setText(memento.getFechaFacturacionCompra());
            TfValorTotal.setText(memento.getValorTotal());
            TfDocumentoProveedor.setText(memento.getDocumentoProveedor());
            TfProductos.setText(memento.getProductos());
        }
    }
    
    public void limpiar()
    {
       TfFechaFacturacionCompra.setText("");
       TfValorTotal.setText("");
       TfDocumentoProveedor.setText("");
       SCantidad.getPreviousValue();
       TfProductos.setText("Escriba el id del producto, para mas información de los productos los puede listar con el botón\n" +
"VER PRODUCTOS");
       
    }
    
    public void  bloquear_cajas()
    {
       TfFechaFacturacionCompra.setEnabled(false);
       TfValorTotal.setEnabled(false);
       TfDocumentoProveedor.setEnabled(false);
       TfProductos.setEnabled(false);       
       BRegistroFacturaCompra.setEnabled(false);
       BCancelarRegistro.setEnabled(false);     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        TfFechaFacturacionCompra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TfValorTotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BRegistroFacturaCompra = new javax.swing.JButton();
        BCancelarRegistro = new javax.swing.JButton();
        BSalir = new javax.swing.JButton();
        TfDocumentoProveedor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TfProductos = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        SCantidad = new javax.swing.JSpinner();
        CBFormaPago = new javax.swing.JComboBox();
        BVerProductos = new javax.swing.JButton();
        TfNumFactura = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        restaurar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Fecha de facturación:");

        TfFechaFacturacionCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfFechaFacturacionCompraActionPerformed(evt);
            }
        });

        jLabel2.setText("Número documento proveedor:");

        jLabel4.setText("Valor total:");

        jLabel5.setText("Productos:");

        BRegistroFacturaCompra.setText("Facturar");
        BRegistroFacturaCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRegistroFacturaCompraActionPerformed(evt);
            }
        });

        BCancelarRegistro.setText("Cancelar");
        BCancelarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancelarRegistroActionPerformed(evt);
            }
        });

        BSalir.setText("Salir");
        BSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSalirActionPerformed(evt);
            }
        });

        TfDocumentoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfDocumentoProveedorActionPerformed(evt);
            }
        });

        jLabel7.setText("Forma de pago:");

        TfProductos.setColumns(20);
        TfProductos.setRows(5);
        TfProductos.setText("Escriba el id del producto, para mas información de los productos los puede listar con el botón\nVER PRODUCTOS");
        TfProductos.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TfProductosAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        TfProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TfProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TfProductos);

        jLabel3.setText("Cantidad:");

        CBFormaPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBFormaPagoActionPerformed(evt);
            }
        });

        BVerProductos.setText("VER PRODUCTOS");
        BVerProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BVerProductosActionPerformed(evt);
            }
        });

        jLabel8.setText("Numero Factura:");

        restaurar.setText("Restaurar");
        restaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaurarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(BVerProductos)
                            .addComponent(jLabel8))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(SCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(CBFormaPago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(TfFechaFacturacionCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TfDocumentoProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BRegistroFacturaCompra)
                                .addGap(18, 18, 18)
                                .addComponent(restaurar)
                                .addGap(129, 129, 129)))))
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(TfNumFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BCancelarRegistro)
                        .addGap(12, 12, 12)
                        .addComponent(BSalir))
                    .addComponent(TfValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TfFechaFacturacionCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(TfDocumentoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CBFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(SCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102)
                .addComponent(jLabel6)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TfValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfNumFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BRegistroFacturaCompra)
                    .addComponent(BCancelarRegistro)
                    .addComponent(BSalir)
                    .addComponent(BVerProductos)
                    .addComponent(restaurar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TfFechaFacturacionCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfFechaFacturacionCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfFechaFacturacionCompraActionPerformed

    private void BSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BSalirActionPerformed

    private void BRegistroFacturaCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRegistroFacturaCompraActionPerformed
       guardarEstado();
        Compra compra = new Compra();
       Proveedor pro = new Proveedor();
       compra.setFechaFacturacionCompra(TfFechaFacturacionCompra.getText());
       pro.setNumeroDocumento(Integer.parseInt(TfDocumentoProveedor.getText()));
       int cantidadValue = (Integer) SCantidad.getValue();
       int formA = CBFormaPago.getSelectedIndex() + 1;
       int idProducto = Integer.parseInt(TfProductos.getText());
       String fecha = compra.getFechaFacturacionCompra();
       con.generarFacturaCompra(formA, pro.getNumeroDocumento(), fecha, cantidadValue, idProducto, TfValorTotal, TfNumFactura);   
       limpiar();
    }//GEN-LAST:event_BRegistroFacturaCompraActionPerformed

    private void BCancelarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancelarRegistroActionPerformed
        // TODO add your handling code here: 
        limpiar();
    }//GEN-LAST:event_BCancelarRegistroActionPerformed

    private void TfDocumentoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfDocumentoProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfDocumentoProveedorActionPerformed

    private void CBFormaPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBFormaPagoActionPerformed
        
    }//GEN-LAST:event_CBFormaPagoActionPerformed

    private void BVerProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BVerProductosActionPerformed
        Principal pri = new Principal();
        ListarProductos pro = new ListarProductos(pri, true);
        pro.setVisible(rootPaneCheckingEnabled);
        pro.toFront();   
    }//GEN-LAST:event_BVerProductosActionPerformed

    private void TfProductosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TfProductosAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TfProductosAncestorAdded

    private void TfProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TfProductosMouseClicked
        TfProductos.setText("");
    }//GEN-LAST:event_TfProductosMouseClicked

    private void restaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaurarActionPerformed
        restaurarEstado();
        bloquear_cajas();
    }//GEN-LAST:event_restaurarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacturacionCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacturacionCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacturacionCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacturacionCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FacturacionCompra dialog = new FacturacionCompra(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCancelarRegistro;
    private javax.swing.JButton BRegistroFacturaCompra;
    private javax.swing.JButton BSalir;
    private javax.swing.JButton BVerProductos;
    private javax.swing.JComboBox CBFormaPago;
    private javax.swing.JSpinner SCantidad;
    private javax.swing.JTextField TfDocumentoProveedor;
    private javax.swing.JTextField TfFechaFacturacionCompra;
    private javax.swing.JTextField TfNumFactura;
    private javax.swing.JTextArea TfProductos;
    private javax.swing.JTextField TfValorTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JButton restaurar;
    // End of variables declaration//GEN-END:variables
}
