/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Controlador.control_existencias;
import Modelo.FormaPago;
import Modelo.Producto;
import Modelo.Venta;
import conexionSQL.conexionSQL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Fernanda
 */
public class FacturacionVenta extends javax.swing.JDialog {
        private conexionSQL cc = new conexionSQL();  
        private Connection cn = cc.conexion();
        private control_existencias con = new control_existencias();
        private Object[][] datostabla;

    public FacturacionVenta(java.awt.Frame parent, boolean modal) {
       super(parent, modal);
       initComponents();
       con.combox(CBFormaPago, "formapago", "descripcionPago");
       TfFechaFacturaVenta.setEnabled(false);
       TfValorTotal.setEnabled(false);
       TFNumFactura.setEnabled(false);
       String fecha = con.obtenerFecha();
       TfFechaFacturaVenta.setText( fecha );
    }
    public void limpiar()
    {
       TfFechaFacturaVenta.setText("");
       TfNombreEmpleado.setText("");
       TfCodigoCliente.setText("");
       TfProductos.setName("Escriba el id del producto");
       CBFormaPago.setName("");
       TfValorTotal.setText("");
    }
    
    public void  bloquear_cajas()
    {
       TfFechaFacturaVenta.setEnabled(false);
       TfNombreEmpleado.setEnabled(false);
       TfCodigoCliente.setEnabled(false);
       TfProductos.setEnabled(false);
       CBFormaPago.setEnabled(false);       
       BRegistroFacturaVenta.setEnabled(false);
       BCancelarRegistro.setEnabled(false);  
       TfValorTotal.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TfFechaFacturaVenta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BRegistroFacturaVenta = new javax.swing.JButton();
        BCancelarRegistro = new javax.swing.JButton();
        BSalir = new javax.swing.JButton();
        TfNombreEmpleado = new javax.swing.JTextField();
        TfCodigoCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TfValorTotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        CBFormaPago = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        SCantidad = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        TFNumFactura = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TfProductos = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Fecha de Facturación:");

        TfFechaFacturaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfFechaFacturaVentaActionPerformed(evt);
            }
        });

        jLabel5.setText("Productos:");

        BRegistroFacturaVenta.setText("Facturar");
        BRegistroFacturaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRegistroFacturaVentaActionPerformed(evt);
            }
        });

        BCancelarRegistro.setText("Cancelar");
        BCancelarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancelarRegistroActionPerformed(evt);
            }
        });

        BSalir.setText("Salir");
        BSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSalirActionPerformed(evt);
            }
        });

        TfNombreEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfNombreEmpleadoActionPerformed(evt);
            }
        });

        TfCodigoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfCodigoClienteActionPerformed(evt);
            }
        });

        jLabel7.setText("Forma de pago:");

        jLabel8.setText("Codigo Cliente");

        jLabel9.setText("Nombre Empleado");

        jLabel10.setText("Valor total");

        CBFormaPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBFormaPagoActionPerformed(evt);
            }
        });

        jLabel3.setText("Cantidad : ");

        jLabel4.setText("Numero Factura :");

        TfProductos.setColumns(20);
        TfProductos.setRows(5);
        TfProductos.setText("Escriba el id del producto");
        TfProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TfProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TfProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel8))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TfFechaFacturaVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                    .addComponent(TfCodigoCliente))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel9)))
                            .addComponent(jLabel3))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TfNombreEmpleado)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CBFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(70, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(TFNumFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BRegistroFacturaVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TfValorTotal, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BCancelarRegistro)
                        .addGap(12, 12, 12)
                        .addComponent(BSalir)))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TfFechaFacturaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(TfNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(CBFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(SCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(79, 79, 79)
                        .addComponent(jLabel6))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BRegistroFacturaVenta)
                    .addComponent(BCancelarRegistro)
                    .addComponent(BSalir)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TFNumFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(161, 161, 161))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
      
    private void TfFechaFacturaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfFechaFacturaVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfFechaFacturaVentaActionPerformed

    private void BSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BSalirActionPerformed

    private void BRegistroFacturaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRegistroFacturaVentaActionPerformed
       Venta venta = new Venta();
       venta.setFechaFact(TfFechaFacturaVenta.getText());
       int formA = CBFormaPago.getSelectedIndex() + 1;
       String nombreEmpleado = TfNombreEmpleado.getText();
       int idProducto = Integer.parseInt(TfProductos.getText());
       String fecha = venta.getFechaFact();
       int cantidadValue = (Integer) SCantidad.getValue();
       int idCliente = Integer.parseInt(TfCodigoCliente.getText());
       con.generarFacturaVenta(idCliente, nombreEmpleado, formA, fecha, cantidadValue, idProducto, TfValorTotal, TFNumFactura);
    }//GEN-LAST:event_BRegistroFacturaVentaActionPerformed

    private void BCancelarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancelarRegistroActionPerformed
        // TODO add your handling code here:
        bloquear_cajas();  
        limpiar();
    }//GEN-LAST:event_BCancelarRegistroActionPerformed

    private void TfNombreEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfNombreEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfNombreEmpleadoActionPerformed

    private void TfCodigoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfCodigoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfCodigoClienteActionPerformed

    private void CBFormaPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBFormaPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBFormaPagoActionPerformed

    private void TfProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TfProductosMouseClicked
        TfProductos.setText("");
    }//GEN-LAST:event_TfProductosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacturacionVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacturacionVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacturacionVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacturacionVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FacturacionVenta dialog = new FacturacionVenta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCancelarRegistro;
    private javax.swing.JButton BRegistroFacturaVenta;
    private javax.swing.JButton BSalir;
    private javax.swing.JComboBox CBFormaPago;
    private javax.swing.JSpinner SCantidad;
    private javax.swing.JTextField TFNumFactura;
    private javax.swing.JTextField TfCodigoCliente;
    private javax.swing.JTextField TfFechaFacturaVenta;
    private javax.swing.JTextField TfNombreEmpleado;
    private javax.swing.JTextArea TfProductos;
    private javax.swing.JTextField TfValorTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public conexionSQL getCc() {
        return cc;
    }

    public void setCc(conexionSQL cc) {
        this.cc = cc;
    }

    public Connection getCn() {
        return cn;
    }

    public void setCn(Connection cn) {
        this.cn = cn;
    }

    public JButton getBCancelarRegistro() {
        return BCancelarRegistro;
    }

    public void setBCancelarRegistro(JButton BCancelarRegistro) {
        this.BCancelarRegistro = BCancelarRegistro;
    }

    public JButton getBRegistroFacturaVenta() {
        return BRegistroFacturaVenta;
    }

    public void setBRegistroFacturaVenta(JButton BRegistroFacturaVenta) {
        this.BRegistroFacturaVenta = BRegistroFacturaVenta;
    }

    public JButton getBSalir() {
        return BSalir;
    }

    public void setBSalir(JButton BSalir) {
        this.BSalir = BSalir;
    }

    public JComboBox<String> getCBFormaPago() {
        return CBFormaPago;
    }

    public void setCBFormaPago(JComboBox<String> CBFormaPago) {
        this.CBFormaPago = CBFormaPago;
    }

    public JTextField getTfCodigoCliente() {
        return TfCodigoCliente;
    }

    public void setTfCodigoCliente(JTextField TfCodigoCliente) {
        this.TfCodigoCliente = TfCodigoCliente;
    }

    public JTextField getTfFechaFactura() {
        return TfFechaFacturaVenta;
    }

    public void setTfFechaFactura(JTextField TfFechaFactura) {
        this.TfFechaFacturaVenta = TfFechaFactura;
    }

    public JTextField getTfNombreEmpleado() {
        return TfNombreEmpleado;
    }

    public void setTfNombreEmpleado(JTextField TfNombreEmpleado) {
        this.TfNombreEmpleado = TfNombreEmpleado;
    }


    public JTextField getTfValorTotal() {
        return TfValorTotal;
    }

    public void setTfValorTotal(JTextField TfValorTotal) {
        this.TfValorTotal = TfValorTotal;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public JTextField getTFNumFactura() {
        return TFNumFactura;
    }

    public void setTFNumFactura(JTextField TFNumFactura) {
        this.TFNumFactura = TFNumFactura;
    }

}
