/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Controlador.control_existencias;
import Modelo.Ciudad;
import Modelo.Cliente;
import Modelo.TipoDocumento;
import conexionSQL.conexionSQL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Fernanda
 */
public class RegistroCliente extends javax.swing.JDialog {
    //Principal pr = new Principal();
    private conexionSQL cc = new conexionSQL();  
    private Connection cn = cc.conexion();
    private control_existencias con = new control_existencias();
    private Object[][] datostabla;
    public RegistroCliente() {
    }

    /**
     * Creates new form RegistroCliente
     */
    public RegistroCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        con.combox(CBCiudad, "ciudad", "nombreCiudad");
        con.combox(CBTipoD, "tipodocumento", "descripcion");
    }
    public void limpiar()
    {
       TfDocumento.setText("");
       CBTipoD.setName("");
       TfNombreC.setText("");
       TfDireccion.setText("");
       TfTelefono.setText("");
       CBCiudad.setName("");
        
    }
    
    public void  bloquear_cajas()
    {
       TfDocumento.setEnabled(false);
       CBTipoD.setEnabled(false);
       TfNombreC.setEnabled(false);
       TfDireccion.setEnabled(false);       
       TfTelefono.setEnabled(false); 
       BotonRegistroC.setEnabled(false);
       BCancelarRegistro.setEnabled(false);
       CBCiudad.setEnabled(false);
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TfDocumento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CBTipoD = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        TfNombreC = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TfDireccion = new javax.swing.JTextField();
        CBCiudad = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        TfTelefono = new javax.swing.JTextField();
        BotonRegistroC = new javax.swing.JButton();
        BCancelarRegistro = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Numero de documento :");

        TfDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfDocumentoActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo de documento");

        CBTipoD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));
        CBTipoD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBTipoDActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre Completo : ");

        TfNombreC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfNombreCActionPerformed(evt);
            }
        });

        jLabel4.setText("Direccion : ");

        jLabel5.setText("Ciudad : ");

        CBCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBCiudadActionPerformed(evt);
            }
        });

        jLabel6.setText("Numero de Telefono : ");

        BotonRegistroC.setText("Registrar");
        BotonRegistroC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistroCActionPerformed(evt);
            }
        });

        BCancelarRegistro.setText("Cancelar");
        BCancelarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancelarRegistroActionPerformed(evt);
            }
        });

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(TfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(39, 39, 39)
                .addComponent(CBCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TfDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(CBTipoD, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TfNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel6)
                        .addGap(34, 34, 34)
                        .addComponent(TfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonRegistroC)
                .addGap(18, 18, 18)
                .addComponent(BCancelarRegistro)
                .addGap(12, 12, 12)
                .addComponent(jButton3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TfDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(CBTipoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TfNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(TfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonRegistroC)
                    .addComponent(BCancelarRegistro)
                    .addComponent(jButton3))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TfDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfDocumentoActionPerformed

    private void TfNombreCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfNombreCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfNombreCActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void BotonRegistroCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistroCActionPerformed
        Cliente cliente = new Cliente();
        cliente.setDocumento(Integer.parseInt(getTfDocumento().getText()));
        cliente.setCodTipoDocument(getCBTipoD().getSelectedIndex()+1);
        cliente.setNombreCompletoC(getTfNombreC().getText());
        cliente.setDireccionC(getTfDireccion().getText());
        cliente.setCodCiudadC(getCBCiudad().getSelectedIndex()+1);
        cliente.setTelefonoC(getTfTelefono().getText());
        con.insertarClienteNuevo(cliente);
    }//GEN-LAST:event_BotonRegistroCActionPerformed

    private void BCancelarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancelarRegistroActionPerformed
        // TODO add your handling code here:
        bloquear_cajas();  
        limpiar();
    }//GEN-LAST:event_BCancelarRegistroActionPerformed

    private void CBTipoDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBTipoDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBTipoDActionPerformed

    private void CBCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBCiudadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegistroCliente dialog = new RegistroCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCancelarRegistro;
    private javax.swing.JButton BotonRegistroC;
    private javax.swing.JComboBox CBCiudad;
    private javax.swing.JComboBox CBTipoD;
    private javax.swing.JTextField TfDireccion;
    private javax.swing.JTextField TfDocumento;
    private javax.swing.JTextField TfNombreC;
    private javax.swing.JTextField TfTelefono;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

    public JButton getBCancelarRegistro() {
        return BCancelarRegistro;
    }

    public void setBCancelarRegistro(JButton BCancelarRegistro) {
        this.BCancelarRegistro = BCancelarRegistro;
    }

    public JButton getBotonRegistroC() {
        return BotonRegistroC;
    }

    public void setBotonRegistroC(JButton BotonRegistroC) {
        this.BotonRegistroC = BotonRegistroC;
    }

    public JComboBox<String> getCBCiudad() {
        return CBCiudad;
    }

    public void setCBCiudad(JComboBox<String> CBCiudad) {
        this.CBCiudad = CBCiudad;
    }

    public JComboBox<String> getCBTipoD() {
        return CBTipoD;
    }

    public void setCBTipoD(JComboBox<String> CBTipoD) {
        this.CBTipoD = CBTipoD;
    }

    public JTextField getTfDireccion() {
        return TfDireccion;
    }

    public void setTfDireccion(JTextField TfDireccion) {
        this.TfDireccion = TfDireccion;
    }

    public JTextField getTfDocumento() {
        return TfDocumento;
    }

    public void setTfDocumento(JTextField TfDocumento) {
        this.TfDocumento = TfDocumento;
    }

    public JTextField getTfNombreC() {
        return TfNombreC;
    }

    public void setTfNombreC(JTextField TfNombreC) {
        this.TfNombreC = TfNombreC;
    }

    public JTextField getTfTelefono() {
        return TfTelefono;
    }

    public void setTfTelefono(JTextField TfTelefono) {
        this.TfTelefono = TfTelefono;
    }

    public JButton getjButton3() {
        return jButton3;
    }

    public void setjButton3(JButton jButton3) {
        this.jButton3 = jButton3;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }
}


