/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Controlador.control_existencias;
import Modelo.Producto;
import conexionSQL.conexionSQL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

import javax.swing.JTextField;

/**
 *
 * @author Fernanda
 */
public class RegistrarProducto extends javax.swing.JDialog {
    private conexionSQL cc = new conexionSQL();  
    private Connection cn = cc.conexion();
    private control_existencias con = new control_existencias();
    private Object[][] datostabla;
    public RegistrarProducto() {
    }
    /**
     * Creates new form RegistroCliente
     */
    public RegistrarProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        TfFechaingreso.setEnabled(false);
        String fecha = con.obtenerFecha();
        TfFechaingreso.setText( fecha );
    }
    public void limpiar()
    {
       TfDescripcionProducto.setText("");
       TfCodigoTipoProducto.setText("");
       TfCodigoProveedor.setText("");
       TfCostoProducto.setText("");
       TfFechaingreso.setText("");
       TfDescripcionProducto.setText("");
       TfStock.setText("");
    }
    
    public void  bloquear_cajas()
    {
       TfDescripcionProducto.setEnabled(false);
       TfCodigoTipoProducto.setEnabled(false);
       TfCodigoProveedor.setEnabled(false);
       TfCostoProducto.setEnabled(false);
       TfDescripcionProducto.setEnabled(false);
       TfStock.setEnabled(false);       
       BRegistroProducto.setEnabled(false);
       BCancelarRegistro.setEnabled(false);
       TfFechaingreso.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TfDescripcionProducto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TfCodigoTipoProducto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TfCodigoProveedor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BRegistroProducto = new javax.swing.JButton();
        BCancelarRegistro = new javax.swing.JButton();
        BSalir = new javax.swing.JButton();
        TfCostoProducto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TfStock = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TfFechaingreso = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre del producto:");

        TfDescripcionProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfDescripcionProductoActionPerformed(evt);
            }
        });

        jLabel2.setText("Costo del producto:");

        jLabel3.setText("Codigo del tipo producto:");

        TfCodigoTipoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfCodigoTipoProductoActionPerformed(evt);
            }
        });

        jLabel4.setText("Codigo del proveedor:");

        BRegistroProducto.setText("Registrar");
        BRegistroProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRegistroProductoActionPerformed(evt);
            }
        });

        BCancelarRegistro.setText("Cancelar");
        BCancelarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancelarRegistroActionPerformed(evt);
            }
        });

        BSalir.setText("Salir");
        BSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSalirActionPerformed(evt);
            }
        });

        TfCostoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfCostoProductoActionPerformed(evt);
            }
        });

        jLabel7.setText("Stock:");

        TfStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfStockActionPerformed(evt);
            }
        });

        jLabel9.setText("Fecha Ingreso: ");

        TfFechaingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfFechaingresoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel6))
                    .addComponent(jLabel9)
                    .addComponent(jLabel7))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TfStock)
                    .addComponent(TfDescripcionProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfCodigoTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfFechaingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(22, 22, 22)
                        .addComponent(TfCostoProducto))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TfCodigoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(153, 153, 153))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BRegistroProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BCancelarRegistro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BSalir)
                .addGap(4, 4, 4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TfDescripcionProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(TfCostoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TfStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TfCodigoTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(TfCodigoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TfFechaingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BRegistroProducto)
                    .addComponent(BCancelarRegistro)
                    .addComponent(BSalir))
                .addGap(12, 12, 12)
                .addComponent(jLabel6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TfDescripcionProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfDescripcionProductoActionPerformed
        
    }//GEN-LAST:event_TfDescripcionProductoActionPerformed

    private void BSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BSalirActionPerformed

    private void BRegistroProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRegistroProductoActionPerformed
        Producto producto = new Producto();
        producto.setDescripcion(getTfDescripcionProducto().getText());
        producto.setPrecioVenta(Double.parseDouble(getTfCostoProducto().getText())*1.1);
        producto.setPrecioCosto(Double.parseDouble(getTfCostoProducto().getText()));
        producto.setStock(Integer.parseInt(getTfStock().getText()));
        producto.setCodigoTipoProducto(Integer.parseInt(getTfCodigoTipoProducto().getText()));
        producto.setCodigoProveedor(Integer.parseInt(getTfCodigoProveedor().getText()));
        producto.setFechaIngreso(getTfFechaingreso().getText());
        con.insertarProductoNuevo(producto);            
    }//GEN-LAST:event_BRegistroProductoActionPerformed

    private void BCancelarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancelarRegistroActionPerformed
        // TODO add your handling code here:
        bloquear_cajas();  
        limpiar();
    }//GEN-LAST:event_BCancelarRegistroActionPerformed

    private void TfCostoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfCostoProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfCostoProductoActionPerformed

    private void TfStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfStockActionPerformed

    private void TfCodigoTipoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfCodigoTipoProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfCodigoTipoProductoActionPerformed

    private void TfFechaingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfFechaingresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfFechaingresoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegistrarProducto dialog = new RegistrarProducto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCancelarRegistro;
    private javax.swing.JButton BRegistroProducto;
    private javax.swing.JButton BSalir;
    private javax.swing.JTextField TfCodigoProveedor;
    private javax.swing.JTextField TfCodigoTipoProducto;
    private javax.swing.JTextField TfCostoProducto;
    private javax.swing.JTextField TfDescripcionProducto;
    private javax.swing.JTextField TfFechaingreso;
    private javax.swing.JTextField TfStock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    public JButton getBCancelarRegistro() {
        return BCancelarRegistro;
    }

    public void setBCancelarRegistro(JButton BCancelarRegistro) {
        this.BCancelarRegistro = BCancelarRegistro;
    }

    public JButton getBRegistroProducto() {
        return BRegistroProducto;
    }

    public void setBRegistroProducto(JButton BRegistroProducto) {
        this.BRegistroProducto = BRegistroProducto;
    }

    public JButton getBSalir() {
        return BSalir;
    }

    public void setBSalir(JButton BSalir) {
        this.BSalir = BSalir;
    }

    public JTextField getTfCodigoProveedor() {
        return TfCodigoProveedor;
    }

    public void setTfCodigoProveedor(JTextField TfCodigoProveedor) {
        this.TfCodigoProveedor = TfCodigoProveedor;
    }

    public JTextField getTfCodigoTipoProducto() {
        return TfCodigoTipoProducto;
    }

    public void setTfCodigoTipoProducto(JTextField TfCodigoTipoProducto) {
        this.TfCodigoTipoProducto = TfCodigoTipoProducto;
    }

    public JTextField getTfCostoProducto() {
        return TfCostoProducto;
    }

    public void setTfCostoProducto(JTextField TfCostoProducto) {
        this.TfCostoProducto = TfCostoProducto;
    }

    public JTextField getTfDescripcionProducto() {
        return TfDescripcionProducto;
    }

    public void setTfDescripcionProducto(JTextField TfDescripcionProducto) {
        this.TfDescripcionProducto = TfDescripcionProducto;
    }

    public JTextField getTfFechaingreso() {
        return TfFechaingreso;
    }

    public void setTfFechaingreso(JTextField TfFechaingreso) {
        this.TfFechaingreso = TfFechaingreso;
    }

    public JTextField getTfNombreProducto() {
        return TfDescripcionProducto;
    }

    public void setTfNombreProducto(JTextField TfNombreProducto) {
        this.TfDescripcionProducto = TfNombreProducto;
    }

    public JTextField getTfStock() {
        return TfStock;
    }

    public void setTfStock(JTextField TfStock) {
        this.TfStock = TfStock;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }


    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }
}
